// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TwoWindowCodedUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfEdit uITbNameEdit = this.UIMainWindowWindow.UITbNameEdit;
            WpfEdit uITbIdEdit = this.UIMainWindowWindow.UITbIdEdit;
            WpfButton uISubmitButton = this.UIMainWindowWindow.UISubmitButton;
            #endregion

            // Type 'Prateek' in 'tbName' text box
            //uITbNameEdit.Text = this.RecordedMethod1Params.UITbNameEditText;

            // Type 'Bhuwania' in 'tbId' text box
            //uITbIdEdit.Text = this.RecordedMethod1Params.UITbIdEditText;

            // Click 'Submit' button
            Mouse.Click(uISubmitButton, new Point(252, 29));
            Assert.AreEqual(UIMainWindowWindow.UItbResultText.DisplayText, UIMainWindow2Window.UItbResult2Text.DisplayText);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIMainWindow2Window UIMainWindow2Window
        {
            get
            {
                if ((this.mUIMainWindow2Window == null))
                {
                    this.mUIMainWindow2Window = new UIMainWindow2Window();
                }
                return this.mUIMainWindow2Window;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIMainWindow2Window mUIMainWindow2Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Prateek' in 'tbName' text box
        /// </summary>
        public string UITbNameEditText = "Prateek";
        
        /// <summary>
        /// Type 'Bhuwania' in 'tbId' text box
        /// </summary>
        public string UITbIdEditText = "Bhuwania";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITbNameEdit
        {
            get
            {
                if ((this.mUITbNameEdit == null))
                {
                    this.mUITbNameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITbNameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tbName";
                    this.mUITbNameEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITbNameEdit;
            }
        }
        
        public WpfEdit UITbIdEdit
        {
            get
            {
                if ((this.mUITbIdEdit == null))
                {
                    this.mUITbIdEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITbIdEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tbId";
                    this.mUITbIdEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITbIdEdit;
            }
        }
        
        public WpfButton UISubmitButton
        {
            get
            {
                if ((this.mUISubmitButton == null))
                {
                    this.mUISubmitButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISubmitButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btSubmit";
                    this.mUISubmitButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISubmitButton;
            }
        }
        
        public WpfText UItbResultText
        {
            get
            {
                if ((this.mUItbResultText == null))
                {
                    this.mUItbResultText = new WpfText(this);
                    #region Search Criteria
                    this.mUItbResultText.SearchProperties[WpfText.PropertyNames.AutomationId] = "tbResult";
                    this.mUItbResultText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUItbResultText;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITbNameEdit;
        
        private WpfEdit mUITbIdEdit;
        
        private WpfButton mUISubmitButton;
        
        private WpfText mUItbResultText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMainWindow2Window : WpfWindow
    {
        
        public UIMainWindow2Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow2";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow2");
            #endregion
        }
        
        #region Properties
        public WpfText UItbResult2Text
        {
            get
            {
                if ((this.mUItbResult2Text == null))
                {
                    this.mUItbResult2Text = new WpfText(this);
                    #region Search Criteria
                    this.mUItbResult2Text.SearchProperties[WpfText.PropertyNames.AutomationId] = "tbResult2";
                    this.mUItbResult2Text.WindowTitles.Add("MainWindow2");
                    #endregion
                }
                return this.mUItbResult2Text;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUItbResult2Text;
        #endregion
    }
}
